import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, RefreshCw, ShieldCheck, Clock3, ArrowRight, Plug, Bell, LoaderCircle } from 'lucide-react';
import type { Snapshot } from '../shared/types';
import { platformNames } from '../shared/types';
import type { CalendarSnapshot, EventRule } from '../shared/calendar';
import { calendarRange, calendarTime } from '../shared/calendar';
import { TravelPanel } from './TravelPanel';
import { safeJoinUrl, venueMapUrl } from '../shared/travel';
import { RequestsInbox } from './RequestsInbox';
import { request } from './api';

export function CalendarWorkspace({ snapshot, connections, planning = false }: { snapshot: Snapshot; connections: () => void; planning?: boolean }) {
  const [data, setData] = useState<CalendarSnapshot | null>(null);
  const [error, setError] = useState(''), [busy, setBusy] = useState('');
  const [now, setNow] = useState(Date.now());
  const [meetingId, setMeetingId] = useState(''), [time, setTime] = useState(''), [transition, setTransition] = useState(10);
  useEffect(() => { const timer = setInterval(() => setNow(Date.now()), 1000); return () => clearInterval(timer); }, []);
  const [eventId, setEventId] = useState(''), [extraMinutes, setExtra] = useState(15), [bufferMinutes, setBuffer] = useState(10);
  const refresh = useCallback(async () => { try { setData(await request<CalendarSnapshot>('/api/calendar/state')); } catch { setError('DayMade is offline. Keep the server running on your Mac.'); } }, []);
  useEffect(() => { void refresh(); const timer = setInterval(() => void refresh(), 2000); return () => clearInterval(timer); }, [refresh]);
  const act = async (name: string, endpoint: string, body = {}) => {
    if (busy) return; setBusy(name); setError('');
    try { await request(`/api/calendar/${endpoint}`, body); } catch (e) { setError((e as Error).message); }
    finally { await refresh(); setBusy(''); }
  };
  if (!data) return <div className="workspace"><p role="status">{error || 'Reading your Calendar connection…'}</p></div>;
  const { day, plan } = data;
  const timezone = day?.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone;
  const today = !!day && now >= day.dayStart && now < day.dayEnd;
  const futureEvents = day?.events.filter(e => !e.allDay && e.busy && e.editable && e.start > now && data.rules[e.id]?.flexible) || [];
  const meeting = futureEvents.find(e => e.id === meetingId) || futureEvents[0];
  const currentEvent = day?.events.find(e => !e.allDay && e.busy && e.start <= now && e.end > now);
  const nextEvent = day?.events.filter(e => !e.allDay && e.busy && e.start > now).sort((a, b) => a.start - b.start)[0];
  const active = !!plan && ['coordinating', 'applying', 'attention', 'uncertain'].includes(plan.status);
  const candidates = day?.events.filter(e => !e.allDay && e.busy && e.start <= now && e.end >= now - 3600000) || [];
  const selected = candidates.some(e => e.id === eventId) ? eventId : candidates.at(-1)?.id || '';
  const friends = snapshot.settings.coworkers.filter(p => p.enabled);
  const setRule = (id: string, value: EventRule) => { if (busy) return; setData(current => current ? { ...current, rules: { ...current.rules, [id]: value } } : current); void act('rule', 'rule', { eventId: id, ...value }); };
  return <div className="workspace calendar-workspace">
    <div className="page-heading"><div><div className="eyebrow">YOUR DAY, WITH ROOM TO ADAPT</div><h1>{planning ? 'Plan with your real day.' : 'A little ahead of your day.'}</h1><p>Apple Calendar on your Mac. Approvals on Telegram. Friends on Discord and Zoom.</p></div><span className="date-badge"><CalendarDays size={16} />{new Intl.DateTimeFormat('en-GB', { dateStyle: 'medium', timeZone: timezone }).format(now)}</span></div>
    <section className="card real-time-card" aria-label="Live calendar status"><div><span className="eyebrow">LIVE TIME</span><time dateTime={new Date(now).toISOString()}>{new Intl.DateTimeFormat('en-GB', { hour: '2-digit', minute: '2-digit', second: '2-digit', timeZone: timezone }).format(now)}</time><small>{timezone}</small></div><div><strong>{currentEvent ? `Now: ${currentEvent.title}` : 'No event happening now'}</strong><p>{nextEvent ? `Next: ${nextEvent.title} · ${calendarTime(nextEvent.start, timezone)} · in ${Math.ceil((nextEvent.start - now) / 60000)} min` : 'No upcoming timed events in the loaded day.'}</p></div></section>
    <p className="calendar-muted">To change a meeting: allow it to be rescheduled, select its friends, then choose a new time below. You approve the request first; your friends agree in Discord or Zoom before Calendar updates.</p>
    {day && <div className="calendar-actions"><button className="button primary" onClick={() => document.getElementById('reschedule-meeting')?.scrollIntoView({ behavior: 'smooth', block: 'center' })}><Clock3 size={16}/>Change a meeting time</button></div>}
    {day && !today && <div className="error-banner" role="status">The loaded calendar is from {day.day}. Refresh today’s events before planning.</div>}
    <div className="calendar-flow" aria-label="Agent workflow"><span><CalendarDays size={16} /> Read your day</span><ArrowRight size={14}/><span><Clock3 size={16}/> Check an overrun</span><ArrowRight size={14}/><span><ShieldCheck size={16}/> You approve</span><ArrowRight size={14}/><span>Friends agree → Calendar updates</span></div>
    {(error || data.error || data.notificationError) && <div className="error-banner" role="alert">{error || data.error || data.notificationError}</div>}
    {plan?.approvedAt && snapshot.integrations.coworkers.some(p => plan.changes.some(c => c.personIds.includes(p.id)) && snapshot.integrations[p.platform].error) && <div className="error-banner" role="status">A messaging connection needs attention. Open Connections to check Discord or Zoom; missing replies stay pending.</div>}
    <section className="card calendar-connect">
      <div className="section-heading"><div><span className="section-icon"><CalendarDays size={18}/></span><h2>Apple Calendar</h2></div><span className={`pill ${data.connected ? 'green' : 'neutral'}`}>{data.paused ? 'Disconnected' : data.connected ? 'Connected' : 'Not connected'}</span></div>
      <p>Connect the calendars already on this Mac. Events in your iCloud calendars sync to your iPhone through the same Apple Account.</p>
      <div className="calendar-actions"><button className="button primary" disabled={!!busy} onClick={() => void act('connect', 'connect')}>{busy === 'connect' ? <LoaderCircle size={16} className="spin"/> : <Plug size={16}/>} {data.connected ? 'Reconnect Calendar' : 'Connect Apple Calendar'}</button>{day && <button className="button secondary" disabled={!!busy || !!data.paused} onClick={() => void act('refresh', 'refresh')}><RefreshCw size={15}/> Refresh day</button>}{!data.paused && (data.connected || day) && <button className="button secondary" disabled={!!busy} onClick={() => void act('disconnect', 'disconnect')}>Disconnect Calendar</button>}<button className="button secondary" onClick={connections}>Set up friends & messaging</button></div>
      {busy === 'connect' && <p role="status">macOS may ask for Calendar access. Choose Allow Full Access for Dayflow Calendar.</p>}
      <label className="calendar-toggle"><input type="checkbox" checked={data.monitoring} disabled={!!busy || !data.connected} onChange={e => void act('monitor', 'monitor', { enabled: e.target.checked })}/><span><strong>Check in on Telegram when an event ends</strong><small>While this Mac and DayMade are running. Tell me “need 15 more minutes” to review what comes next. This does not track your iPhone location.</small></span><Bell size={18}/></label>
      {data.refreshedAt && <p className="calendar-muted">Last read {calendarTime(data.refreshedAt, timezone)} · {timezone} · {day?.calendars.length} calendars · Telegram {snapshot.integrations.telegram.connected ? 'connected' : 'needs setup'}</p>}
    </section>
    <TravelPanel calendar={data} now={now} telegramReady={snapshot.integrations.telegram.connected} onPlan={() => void refresh()}/>
    {!planning && <RequestsInbox ready={data.connected && snapshot.integrations.ready}/>}
    {day && <div className="calendar-grid"><section className="card calendar-day"><div className="section-heading"><div><h2>Your whole day</h2></div><span className="tiny-label">{day.events.length} EVENTS</span></div><p className="calendar-muted">Choose what can move and who belongs to each event. Events with no selected friends are treated as personal time.</p>
      {!day.events.length && <div className="calendar-empty"><CalendarDays size={30}/><h3>A clear day.</h3><p>No events today. Add events in Apple Calendar, then refresh. For an iPhone demo, put them in an iCloud calendar.</p></div>}
      {[...day.events].sort((a, b) => a.start - b.start).map(event => {
        const rule = data.rules[event.id] || { flexible: false, personIds: [] };
        return <article key={event.id} className={`calendar-event ${event.end < now ? 'past' : ''}`}><div className="calendar-event-heading"><span className="calendar-event-time">{event.allDay ? 'All day' : calendarRange(event.start, event.end, timezone)}</span><span className={`pill ${rule.flexible ? 'green' : 'neutral'}`}>{rule.flexible ? 'Flexible' : 'Fixed'}</span></div><h3>{event.title}</h3><p className="calendar-muted">{event.calendarName}{event.location ? ` · ${event.location}` : event.online ? ' · Online' : ' · No venue in Calendar'}{event.recurring ? ' · recurring occurrence' : ''}</p>
          {event.online ? <div className="event-venue"><span className="pill green">Online · no travel</span>{safeJoinUrl(event.joinUrl) ? <a href={safeJoinUrl(event.joinUrl)!} target="_blank" rel="noreferrer">Join meeting ↗</a> : <span className="calendar-muted">No join link in Calendar</span>}</div> : venueMapUrl(event) && <div className="event-venue"><a href={venueMapUrl(event)!} target="_blank" rel="noreferrer">View real venue in Apple Maps ↗</a></div>}
          <p className="calendar-muted">{event.allDay ? 'All day' : event.end <= now ? 'Ended' : event.start <= now ? 'Happening now' : `Starts in ${Math.ceil((event.start - now) / 60000)} min`}</p>
          {event.end >= now && <><label className="calendar-checkbox"><input type="checkbox" checked={rule.flexible} disabled={!!busy || active || !event.editable || event.start < now} onChange={e => setRule(event.id, { ...rule, flexible: e.target.checked })}/> Allow this event to be rescheduled</label>{!event.editable && <p className="calendar-muted">{event.hasAttendees ? 'Calendar invitations stay fixed. Use a personal event for Discord plans.' : 'All-day or read-only event: cannot move automatically.'}</p>}
          {rule.flexible && <fieldset className="calendar-friends" disabled={!!busy || active}><legend>Ask these friends before moving</legend>{friends.length ? friends.map(person => <label key={person.id}><input type="checkbox" checked={rule.personIds.includes(person.id)} onChange={e => setRule(event.id, { ...rule, personIds: e.target.checked ? [...rule.personIds, person.id] : rule.personIds.filter(id => id !== person.id) })}/>{person.name} <small>{platformNames[person.platform]}</small></label>) : <p className="calendar-muted">Add friends in Connections to coordinate a meeting.</p>}{!rule.personIds.length && <p className="calendar-muted">Personal time · no messages will be sent for this event.</p>}</fieldset>}</>}
          {rule.flexible && event.editable && event.start > now && <button className="button secondary" disabled={!!busy || active || !today || !data.connected} onClick={() => { setMeetingId(event.id); setTime(''); document.getElementById('reschedule-meeting')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); }}>{rule.personIds.length ? 'Change time & ask friends' : 'Change time'}</button>}
        </article>;
      })}
    </section><div className="calendar-right"><section className="card calendar-reschedule" id="reschedule-meeting"><div className="section-heading"><div><h2>Move a meeting</h2></div><Clock3 size={18}/></div><p>Choose a future flexible event. I’ll check the requested time against your whole day and preserve its duration.</p>
      <form onSubmit={e => { e.preventDefault(); void act('reschedule', 'reschedule', { eventId: meeting?.id, time, day: day.day, bufferMinutes: transition }); }}>
        <label>Meeting to reschedule<select value={meeting?.id || ''} disabled={!!busy || active || !today || !data.connected} onChange={e => { setMeetingId(e.target.value); setTime(''); }}>{!futureEvents.length && <option value="">No future flexible events</option>}{futureEvents.map(e => <option key={e.id} value={e.id}>{e.title} · {calendarRange(e.start, e.end, timezone)}</option>)}</select></label>
        <div className="calendar-inputs"><label>New start time ({timezone})<input type="text" lang="en-GB" placeholder="HH:mm" title="24-hour time, for example 18:30" pattern="([01][0-9]|2[0-3]):[0-5][0-9]" maxLength={5} autoComplete="off" onInvalid={e => e.currentTarget.setCustomValidity('Enter a 24-hour time, for example 18:30.')} onInput={e => e.currentTarget.setCustomValidity('')} required value={time} onChange={e => setTime(e.target.value)} disabled={!!busy || active}/></label><label>Transition buffer (minutes)<input type="number" required min={0} max={60} value={transition} onChange={e => setTransition(Number(e.target.value))} disabled={!!busy || active}/></label></div>
        <button className="button primary" disabled={!!busy || active || !meeting || !time || !today || !data.connected}>{busy === 'reschedule' ? 'Checking Calendar…' : 'Review meeting change'}</button>
      </form>{!futureEvents.length && <p className="calendar-muted">Enable “Allow this event to be rescheduled” on a future event and select its friends in the timeline. If your day is finished, add a future event in Apple Calendar and refresh.</p>}
      <p className="calendar-muted">Today’s date and this Calendar timezone apply. This form uses the transition buffer you enter. Use the Apple Maps check above to plan around your actual route.</p>
    </section><section className="card calendar-overrun"><div className="section-heading"><div><h2>Need a little longer?</h2></div><Clock3 size={18}/></div><p>I’ll calculate the effect on every later event, keep durations intact and use gaps where possible.</p><form onSubmit={e => { e.preventDefault(); void act('preview', 'preview', { eventId: selected, extraMinutes, bufferMinutes }); }}><label>Current or recently ended event<select value={selected} onChange={e => setEventId(e.target.value)} disabled={!candidates.length || active}>{!candidates.length && <option value="">No event happening now</option>}{candidates.map(e => <option key={e.id} value={e.id}>{e.title}</option>)}</select></label><div className="calendar-inputs"><label>More minutes needed<input type="number" min={5} max={120} value={extraMinutes} onChange={e => setExtra(Number(e.target.value))}/></label><label>Transition buffer (minutes)<input type="number" min={0} max={60} value={bufferMinutes} onChange={e => setBuffer(Number(e.target.value))}/></label></div><button className="button primary" disabled={!!busy || active || !selected || !today || !data.connected}>{busy === 'preview' ? 'Reviewing your day…' : 'Review the rest of my day'}</button></form><p className="calendar-muted">Extra time begins at the later of now or the scheduled end. The current event’s stored end time stays as it is.</p></section>
    {plan && <section className="card calendar-plan"><div className="section-heading"><div><h2>Your proposed changes</h2></div><span className={`pill ${plan.status === 'applied' ? 'green' : 'neutral'}`}>{plan.status}</span></div><p>{plan.peer ? plan.peer.reason : plan.reschedule ? <>Reschedule “{plan.source.title}” on {plan.day}, with {plan.bufferMinutes} minutes between events.</> : <>Finish “{plan.source.title}” around <strong>{calendarTime(plan.assumedEnd, plan.timezone)}</strong>, then allow {plan.bufferMinutes} minutes between events.</>}</p>
      {plan.blockers.length > 0 && <div className="error-banner" role="status"><div><strong>This plan needs your help.</strong>{plan.blockers.map((b, i) => <p key={i}>{b}</p>)}</div></div>}
      {plan.error && <div className="error-banner" role="status">{plan.error}</div>}
      {!plan.changes.length && !plan.blockers.length && <p className="calendar-success">Your later events have enough room. No changes needed.</p>}
      {plan.changes.map(change => <article className="calendar-change" key={change.event.id}><h3>{change.event.title}</h3><div className="calendar-before-after"><span>{calendarRange(change.event.start, change.event.end, plan.timezone)}</span><ArrowRight size={16}/><strong>{calendarRange(change.start, change.end, plan.timezone)}</strong></div>{change.conversation?.proposal ? <><p className="calendar-muted">{change.conversation.proposal.destinationName}{change.conversation.proposal.negotiation ? ` · Round ${change.conversation.proposal.negotiation.round}/${change.conversation.proposal.negotiation.maxRounds}` : ''}</p>{!!change.conversation.proposal.negotiation?.history.length && <details className="negotiation-history"><summary>Previous proposals</summary>{change.conversation.proposal.negotiation.history.map(round => <p key={round.id}><strong>{round.time}–{round.endTime}</strong> · {round.people.map(person => `${person.name}: ${person.text || person.status}`).join('; ')}<br/>{round.reason}</p>)}</details>}<div className="calendar-message">{change.conversation.proposal.text}</div>{change.conversation.proposal.people.map(person => <div className="calendar-reply" key={person.id}><strong>{person.name}</strong><small>{platformNames[person.platform!]} · {person.address}</small><span>{person.delivery === 'not_sent' ? 'Awaiting your approval' : `${person.delivery} · ${person.status}`}</span>{person.text && <p>“{person.text}”</p>}{person.deliveryError && <p>{person.deliveryError}</p>}</div>)}</> : <p className="calendar-muted">Personal event · no messages</p>}</article>)}
      {plan.status === 'draft' && plan.changes.length > 0 && !plan.blockers.length && <><p className="calendar-muted">LIVE ACTION · {plan.day} · {plan.timezone}. {plan.automatic ? 'Approve once: I’ll check Calendar and negotiate alternative times today with these same friends, keeping the duration. Up to 6 proposals over 30 minutes. Calendar saves only after everyone agrees to the latest time.' : 'This older plan approves only the times shown. Build a fresh plan to delegate automatic negotiation.'}</p><button className="button primary calendar-approve" disabled={!!busy || now >= plan.expiresAt} onClick={() => void act('approve', 'approve', { id: plan.id })}>{plan.automatic ? 'Let DayMade coordinate & update Calendar' : 'Approve messages & calendar changes'}</button><button className="button secondary" disabled={!!busy || now >= plan.expiresAt} onClick={() => void act('notify', 'notify')}>Send approval to my Telegram</button><p className="calendar-muted">{now >= plan.expiresAt ? 'Approval expired. Review the day again.' : 'Approval expires 10 minutes after this plan was created.'}</p></>}
      {plan.status === 'applied' && <p className="calendar-success"><ShieldCheck size={18}/> {plan.receipts?.length} calendar changes saved. iCloud will sync them to your iPhone.</p>}
      {!['applied', 'dismissed', 'applying', 'unresolved'].includes(plan.status) && <button className="button secondary" disabled={!!busy} onClick={() => void act('dismiss', 'dismiss', { id: plan.id })}>{plan.approvedAt ? 'Stop this plan' : 'Dismiss plan'}</button>}
    </section>}
    <section className="card activity-card" id="activity"><div className="section-heading"><div><h2>Planning activity</h2></div></div>{plan ? <><p className="calendar-muted">{plan.day} · {plan.status}</p>{plan.changes.flatMap(c => c.conversation?.activity || []).sort((a, b) => b.at - a.at).slice(0, 8).map(item => <div className="activity-item" key={item.id}><span className={`activity-dot ${item.kind}`}/><div><strong>{item.title}</strong><p>{item.detail}</p></div><time>{calendarTime(item.at, timezone)}</time></div>)}{!plan.changes.some(c => c.conversation?.activity?.length) && <p className="calendar-muted">Your plan and any Calendar save receipts appear above.</p>}</> : <p className="calendar-muted">Review a real meeting change or report an overrun to start a plan.</p>}</section>
    <div className="trust-note"><ShieldCheck size={18}/><p><strong>You decide what moves.</strong> Fixed appointments and calendar invitations are protected. If a friend declines or suggests another time, I’ll check Calendar, coordinate the next suitable slot and report the final result.</p></div></div></div>}
  </div>;
}
