import { useCallback, useEffect, useState } from 'react';
import { CalendarDays, RefreshCw, ShieldCheck, Clock3, ArrowRight, Plug, Bell, LoaderCircle } from 'lucide-react';
import type { Snapshot } from '../shared/types';
import { platformNames } from '../shared/types';
import type { CalendarSnapshot, EventRule } from '../shared/calendar';
import { calendarRange, calendarTime } from '../shared/calendar';
import { request } from './api';

export function CalendarWorkspace({ snapshot, connections, practice }: { snapshot: Snapshot; connections: () => void; practice: () => void }) {
  const [data, setData] = useState<CalendarSnapshot | null>(null);
  const [error, setError] = useState(''), [busy, setBusy] = useState('');
  const [eventId, setEventId] = useState(''), [extraMinutes, setExtra] = useState(15), [bufferMinutes, setBuffer] = useState(10);
  const refresh = useCallback(async () => { try { setData(await request<CalendarSnapshot>('/api/calendar/state')); } catch { setError('Dayflow is offline. Keep the server running on your Mac.'); } }, []);
  useEffect(() => { void refresh(); const timer = setInterval(() => void refresh(), 2000); return () => clearInterval(timer); }, [refresh]);
  const act = async (name: string, endpoint: string, body = {}) => {
    if (busy) return; setBusy(name); setError('');
    try { await request(`/api/calendar/${endpoint}`, body); } catch (e) { setError((e as Error).message); }
    finally { await refresh(); setBusy(''); }
  };
  if (!data) return <div className="workspace"><p role="status">{error || 'Reading your Calendar connection…'}</p></div>;
  const { day, plan } = data;
  const now = Date.now(), timezone = day?.timezone || Intl.DateTimeFormat().resolvedOptions().timeZone;
  const active = !!plan && ['coordinating', 'applying', 'attention', 'uncertain'].includes(plan.status);
  const candidates = day?.events.filter(e => !e.allDay && e.busy && e.start <= now && e.end >= now - 3600000) || [];
  const selected = candidates.some(e => e.id === eventId) ? eventId : candidates.at(-1)?.id || '';
  const friends = snapshot.settings.coworkers.filter(p => p.enabled);
  const setRule = (id: string, value: EventRule) => { if (busy) return; setData(current => current ? { ...current, rules: { ...current.rules, [id]: value } } : current); void act('rule', 'rule', { eventId: id, ...value }); };
  return <div className="workspace calendar-workspace">
    <div className="page-heading"><div><div className="eyebrow">YOUR DAY, WITH ROOM TO ADAPT</div><h1>A little ahead of your day.</h1><p>Apple Calendar on your Mac. Approvals on Telegram. Friends on Discord and Zoom.</p></div><span className="date-badge"><CalendarDays size={16} />{day?.day || 'My calendar'}</span></div>
    <div className="calendar-flow" aria-label="Agent workflow"><span><CalendarDays size={16} /> Read your day</span><ArrowRight size={14}/><span><Clock3 size={16}/> Check an overrun</span><ArrowRight size={14}/><span><ShieldCheck size={16}/> You approve</span><ArrowRight size={14}/><span>Friends agree → Calendar updates</span></div>
    {(error || data.error || data.notificationError) && <div className="error-banner" role="alert">{error || data.error || data.notificationError}</div>}
    {snapshot.state.mode === 'live' && ['approval', 'preparing', 'sending', 'waiting', 'attention', 'uncertain'].includes(snapshot.state.phase) && <section className="delivery-notice"><div><strong>Your existing conversation is still active.</strong><p>Review its replies in Practice scenario, then finish monitoring before starting a calendar plan.</p></div><button className="button secondary" onClick={practice}>Review current conversation</button></section>}
    {plan?.approvedAt && snapshot.integrations.coworkers.some(p => plan.changes.some(c => c.personIds.includes(p.id)) && snapshot.integrations[p.platform].error) && <div className="error-banner" role="status">A messaging connection needs attention. Open Connections to check Discord or Zoom; missing replies stay pending.</div>}
    <section className="card calendar-connect">
      <div className="section-heading"><div><span className="section-icon"><CalendarDays size={18}/></span><h2>Apple Calendar</h2></div><span className={`pill ${data.connected ? 'green' : 'neutral'}`}>{data.connected ? 'Connected' : 'Not connected'}</span></div>
      <p>Connect the calendars already on this Mac. Events in your iCloud calendars sync to your iPhone through the same Apple Account.</p>
      <div className="calendar-actions"><button className="button primary" disabled={!!busy} onClick={() => void act('connect', 'connect')}>{busy === 'connect' ? <LoaderCircle size={16} className="spin"/> : <Plug size={16}/>} {data.connected ? 'Reconnect Calendar' : 'Connect Apple Calendar'}</button>{day && <button className="button secondary" disabled={!!busy} onClick={() => void act('refresh', 'refresh')}><RefreshCw size={15}/> Refresh day</button>}<button className="button secondary" onClick={connections}>Set up friends & messaging</button></div>
      {busy === 'connect' && <p role="status">macOS may ask for Calendar access. Choose Allow Full Access for Dayflow Calendar.</p>}
      <label className="calendar-toggle"><input type="checkbox" checked={data.monitoring} disabled={!!busy || !data.connected} onChange={e => void act('monitor', 'monitor', { enabled: e.target.checked })}/><span><strong>Check in on Telegram when an event ends</strong><small>While this Mac and Dayflow are running. Tell me “need 15 more minutes” to review what comes next. This does not track your iPhone location.</small></span><Bell size={18}/></label>
      {data.refreshedAt && <p className="calendar-muted">Last read {calendarTime(data.refreshedAt, timezone)} · {timezone} · {day?.calendars.length} calendars · Telegram {snapshot.integrations.telegram.connected ? 'connected' : 'needs setup'}</p>}
    </section>
    {day && <div className="calendar-grid"><section className="card calendar-day"><div className="section-heading"><div><h2>Your whole day</h2></div><span className="tiny-label">{day.events.length} EVENTS</span></div><p className="calendar-muted">Choose what can move and who belongs to each event. Events with no selected friends are treated as personal time.</p>
      {!day.events.length && <div className="calendar-empty"><CalendarDays size={30}/><h3>A clear day.</h3><p>No events today. Add events in Apple Calendar, then refresh. For an iPhone demo, put them in an iCloud calendar.</p></div>}
      {day.events.map(event => {
        const rule = data.rules[event.id] || { flexible: false, personIds: [] };
        return <article key={event.id} className={`calendar-event ${event.end < now ? 'past' : ''}`}><div className="calendar-event-heading"><span className="calendar-event-time">{event.allDay ? 'All day' : calendarRange(event.start, event.end, timezone)}</span><span className={`pill ${rule.flexible ? 'green' : 'neutral'}`}>{rule.flexible ? 'Flexible' : 'Fixed'}</span></div><h3>{event.title}</h3><p className="calendar-muted">{event.calendarName}{event.location ? ` · ${event.location}` : ''}{event.recurring ? ' · recurring occurrence' : ''}</p>
          {event.end >= now && <><label className="calendar-checkbox"><input type="checkbox" checked={rule.flexible} disabled={!!busy || active || !event.editable || event.start < now} onChange={e => setRule(event.id, { ...rule, flexible: e.target.checked })}/> Allow this event to move later</label>{!event.editable && <p className="calendar-muted">{event.hasAttendees ? 'Calendar invitations stay fixed. Use a personal event for Discord plans.' : 'All-day or read-only event: cannot move automatically.'}</p>}
          {rule.flexible && <fieldset className="calendar-friends" disabled={!!busy || active}><legend>Ask these friends before moving</legend>{friends.length ? friends.map(person => <label key={person.id}><input type="checkbox" checked={rule.personIds.includes(person.id)} onChange={e => setRule(event.id, { ...rule, personIds: e.target.checked ? [...rule.personIds, person.id] : rule.personIds.filter(id => id !== person.id) })}/>{person.name} <small>{platformNames[person.platform]}</small></label>) : <p className="calendar-muted">Add friends in Connections to coordinate a meeting.</p>}{!rule.personIds.length && <p className="calendar-muted">Personal time · no messages will be sent for this event.</p>}</fieldset>}</>}
        </article>;
      })}
    </section><div className="calendar-right"><section className="card calendar-overrun"><div className="section-heading"><div><h2>Need a little longer?</h2></div><Clock3 size={18}/></div><p>I’ll calculate the effect on every later event, keep durations intact and use gaps where possible.</p><form onSubmit={e => { e.preventDefault(); void act('preview', 'preview', { eventId: selected, extraMinutes, bufferMinutes }); }}><label>Current or recently ended event<select value={selected} onChange={e => setEventId(e.target.value)} disabled={!candidates.length || active}>{!candidates.length && <option value="">No event happening now</option>}{candidates.map(e => <option key={e.id} value={e.id}>{e.title}</option>)}</select></label><div className="calendar-inputs"><label>More minutes needed<input type="number" min={5} max={120} value={extraMinutes} onChange={e => setExtra(Number(e.target.value))}/></label><label>Travel / transition minutes<input type="number" min={0} max={60} value={bufferMinutes} onChange={e => setBuffer(Number(e.target.value))}/></label></div><button className="button primary" disabled={!!busy || active || !selected}>{busy === 'preview' ? 'Reviewing your day…' : 'Review the rest of my day'}</button></form><p className="calendar-muted">Extra time begins at the later of now or the scheduled end. The current event’s stored end time stays as it is.</p></section>
    {plan && <section className="card calendar-plan"><div className="section-heading"><div><h2>Your proposed changes</h2></div><span className={`pill ${plan.status === 'applied' ? 'green' : 'neutral'}`}>{plan.status}</span></div><p>Finish “{plan.source.title}” around <strong>{calendarTime(plan.assumedEnd, plan.timezone)}</strong>, then allow {plan.bufferMinutes} minutes between events.</p>
      {plan.blockers.length > 0 && <div className="error-banner" role="status"><div><strong>This plan needs your help.</strong>{plan.blockers.map((b, i) => <p key={i}>{b}</p>)}</div></div>}
      {plan.error && <div className="error-banner" role="status">{plan.error}</div>}
      {!plan.changes.length && !plan.blockers.length && <p className="calendar-success">Your later events have enough room. No changes needed.</p>}
      {plan.changes.map(change => <article className="calendar-change" key={change.event.id}><h3>{change.event.title}</h3><div className="calendar-before-after"><span>{calendarRange(change.event.start, change.event.end, plan.timezone)}</span><ArrowRight size={16}/><strong>{calendarRange(change.start, change.end, plan.timezone)}</strong></div>{change.conversation?.proposal ? <><p className="calendar-muted">{change.conversation.proposal.destinationName}</p><div className="calendar-message">{change.conversation.proposal.text}</div>{change.conversation.proposal.people.map(person => <div className="calendar-reply" key={person.id}><strong>{person.name}</strong><small>{platformNames[person.platform!]} · {person.address}</small><span>{person.delivery === 'not_sent' ? 'Awaiting your approval' : `${person.delivery} · ${person.status}`}</span>{person.text && <p>“{person.text}”</p>}{person.deliveryError && <p>{person.deliveryError}</p>}</div>)}</> : <p className="calendar-muted">Personal event · no messages</p>}</article>)}
      {plan.status === 'draft' && plan.changes.length > 0 && !plan.blockers.length && <><p className="calendar-muted">LIVE ACTION · {plan.day} · {plan.timezone}. Approval sends these exact messages. Calendar saves only after every named friend agrees. Silent or unclear replies never count as agreement.</p><button className="button primary calendar-approve" disabled={!!busy || now >= plan.expiresAt} onClick={() => void act('approve', 'approve', { id: plan.id })}>Approve messages & calendar changes</button><button className="button secondary" disabled={!!busy || now >= plan.expiresAt} onClick={() => void act('notify', 'notify')}>Send approval to my Telegram</button><p className="calendar-muted">{now >= plan.expiresAt ? 'Approval expired. Review the day again.' : 'Approval expires 10 minutes after this plan was created.'}</p></>}
      {plan.status === 'applied' && <p className="calendar-success"><ShieldCheck size={18}/> {plan.receipts?.length} calendar changes saved. iCloud will sync them to your iPhone.</p>}
      {!['applied', 'dismissed', 'applying'].includes(plan.status) && <button className="button secondary" disabled={!!busy} onClick={() => void act('dismiss', 'dismiss', { id: plan.id })}>{plan.approvedAt ? 'Stop this plan' : 'Dismiss plan'}</button>}
    </section>}
    <div className="trust-note"><ShieldCheck size={18}/><p><strong>You decide what moves.</strong> Fixed appointments and calendar invitations are protected. If a friend suggests another time, I’ll pause and ask you to review a fresh plan.</p></div></div></div>}
  </div>;
}
