import { useEffect, useRef, useState } from 'react';
import { ArrowRight, ArrowUpRight, CheckCheck, Copy, LoaderCircle, MessageCircle, Plug, Send, ShieldCheck, Sparkles, Users, Video, X } from 'lucide-react';
import { platformNames, type Coworker, type CoworkerPlatform, type Platform, type Snapshot } from '../shared/types';
import { request } from './api';

export function Connections({ snapshot, refresh, close, initialTab = 'telegram' }: { initialTab?: Platform; snapshot: Snapshot; refresh: () => Promise<void>; close: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [tab, setTab] = useState<Platform | 'model'>(initialTab);
  const [form, setForm] = useState({ telegramToken: '', discordToken: '', discordChannelId: snapshot.settings.discordChannelId, zoomClientId: snapshot.settings.zoomClientId, zoomClientSecret: '', zoomRedirectBaseUrl: snapshot.settings.zoomRedirectBaseUrl, ollamaUrl: snapshot.settings.ollamaUrl, ollamaModel: snapshot.settings.ollamaModel });
  const [people, setPeople] = useState<Coworker[]>(snapshot.settings.coworkers);
  const [busy, setBusy] = useState('');
  const [error, setError] = useState('');
  const [message, setMessage] = useState('');
  const [zoomUrl, setZoomUrl] = useState('');
  const i = snapshot.integrations;
  useEffect(() => { dialog.current?.showModal(); return () => dialog.current?.close(); }, []);
  useEffect(() => { setForm(f => ({ ...f, zoomRedirectBaseUrl: snapshot.settings.zoomRedirectBaseUrl })); }, [snapshot.settings.zoomRedirectBaseUrl]);
  const run = async (name: string, action: () => Promise<unknown>) => {
    if (busy) return;
    setBusy(name); setError(''); setMessage('');
    try { await action(); await refresh(); }
    catch (e) { setError((e as Error).message); }
    finally { setBusy(''); }
  };
  const save = async (data: object) => { await request('/api/settings', data); setForm(f => ({ ...f, telegramToken: '', discordToken: '', zoomClientSecret: '' })); };
  const field = (key: keyof typeof form) => ({ value: form[key], onChange: (event: React.ChangeEvent<HTMLInputElement>) => setForm({ ...form, [key]: event.target.value.trim() }) });
  const copy = (text: string) => run('copy', async () => { await navigator.clipboard.writeText(text); setMessage('Copied.'); });
  const updatePerson = (id: string, values: Partial<Coworker>) => setPeople(current => current.map(p => p.id === id ? { ...p, ...values } : p));
  const savePeople = async () => { await save({ coworkers: people }); setMessage('Coworkers saved. Proposals will use their selected Discord or Zoom destination.'); };
  const selected = people.filter(p => p.enabled).length;
  return <dialog ref={dialog} className="connections-dialog" onCancel={close} onClick={event => { if (event.target === dialog.current) close(); }} aria-labelledby="connections-title">
    <div className="dialog-header"><div><span className="eyebrow">ONE AGENT. YOUR PEOPLE.</span><h2 id="connections-title">Your tools, working together.</h2><p>Telegram connects you to Dayflow. Discord and Zoom connect you to coworkers.</p></div><button className="icon-button" onClick={close} aria-label="Close connections"><X size={21} /></button></div>
    <div className="dialog-body">
      {(error || message) && <div className={error ? 'error-banner' : 'success-banner'} role={error ? 'alert' : 'status'}>{error || message}</div>}
      <div className="setup-tabs" role="tablist" aria-label="Platform setup">{(['telegram', 'discord', 'zoom', 'model'] as const).map(platform => <button role="tab" aria-selected={tab === platform} aria-controls={`setup-${platform}`} id={`tab-${platform}`} key={platform} className={tab === platform ? 'selected' : ''} onClick={() => setTab(platform)} onKeyDown={event => { const tabs = ['telegram', 'discord', 'zoom', 'model'] as const; let next = tabs.indexOf(platform); if (event.key === 'ArrowRight') next = (next + 1) % tabs.length; else if (event.key === 'ArrowLeft') next = (next + tabs.length - 1) % tabs.length; else if (event.key === 'Home') next = 0; else if (event.key === 'End') next = tabs.length - 1; else return; event.preventDefault(); setTab(tabs[next]); document.getElementById(`tab-${tabs[next]}`)?.focus(); }} tabIndex={tab === platform ? 0 : -1}>{platform === 'telegram' ? <Send size={16} /> : platform === 'discord' ? <MessageCircle size={16} /> : platform === 'zoom' ? <Video size={16} /> : <Sparkles size={16} />}{platform === 'model' ? 'Open model' : platform === 'zoom' ? 'Zoom' : platformNames[platform]}</button>)}</div>
      {tab === 'telegram' && <section className="setup-section" role="tabpanel" id="setup-telegram" aria-labelledby="tab-telegram">
        <div className="setup-heading"><span className="integration-icon telegram-icon"><Send size={23} /></span><div><h3>Telegram</h3><p>Your private channel with Dayflow: suggestions, approvals and updates.</p></div><span className={`pill ${i.telegram.connected && i.telegram.paired ? 'green' : 'neutral'}`}>{i.telegram.connected && i.telegram.paired ? 'Owner connected' : i.telegram.paired ? 'Paired · reconnect' : 'Pair your phone'}</span></div>
        <details className="setup-instructions" open={!i.telegram.configured}><summary>Connect your phone first</summary><ol><li>Open the verified <strong>@BotFather</strong> in Telegram and send <code>/newbot</code>.</li><li>Choose a name and username ending in <code>bot</code>. Paste its token below.</li><li>Click <strong>Save & pair Telegram</strong>, open your owner pairing link and tap <strong>Start</strong>.</li><li>Add your coworkers below using Discord or Zoom Team Chat.</li></ol><p>Keep your owner pairing link private. Only your account uses this Telegram bot.</p></details>
        <label>Telegram bot token<input type="password" {...field('telegramToken')} placeholder={i.telegram.configured ? 'Saved — leave blank to keep it' : '123456789:your-bot-token'} autoComplete="new-password" /></label>
        <button className="button secondary" disabled={!!busy} onClick={() => void run('telegram', async () => { await save({ telegramToken: form.telegramToken }); await request('/api/telegram/connect', {}); })}>{busy === 'telegram' ? <LoaderCircle size={16} className="spin" /> : <Send size={16} />}{i.telegram.paired ? 'Check Telegram connection' : 'Save & pair Telegram'}</button>
        {i.telegram.username && i.telegram.pairingCode && <div className="auth-card"><p>Open this private owner link on your phone and tap Start. It expires in 10 minutes.</p><a className="button primary" href={`https://t.me/${i.telegram.username}?start=${i.telegram.pairingCode}`} target="_blank" rel="noreferrer">Pair @{i.telegram.username}<ArrowUpRight size={15} /></a></div>}
        {i.telegram.paired && <p className="connected-note"><CheckCheck size={15} /> Your private agent connection is saved. Coworker messages go through Discord and Zoom.</p>}
        {i.telegram.error && <p className="inline-error">{i.telegram.error}</p>}
        <p className="setup-note">Dayflow asks for your approval and reports coworker responses here. No public URL or extra messaging service is needed.</p>
      </section>}
      {tab === 'discord' && <section className="setup-section" role="tabpanel" id="setup-discord" aria-labelledby="tab-discord">
        <div className="setup-heading"><span className="integration-icon discord-icon"><MessageCircle size={23} /></span><div><h3>Discord</h3><p>Mention each coworker in one dedicated server text channel.</p></div><span className={`pill ${i.discord.connected ? 'green' : 'neutral'}`}>{i.discord.connected ? `#${i.discord.channelName}` : 'Not connected'}</span></div>
        <ol className="connection-steps"><li>In the <a href="https://discord.com/developers/applications" target="_blank" rel="noreferrer">Discord Developer Portal</a>, create an application. Open <strong>Bot</strong> and copy its bot token.</li><li>Under Bot, enable <strong>Message Content Intent</strong> so Dayflow can interpret replies.</li><li>Under <strong>Installation</strong>, use <strong>Guild Install</strong> with <code>bot</code> scope. Grant <strong>View Channels, Send Messages, Read Message History</strong>. Open the install link and add it to your demo server.</li><li>In Discord, enable <strong>User Settings → Advanced → Developer Mode</strong>. Right-click the text channel → <strong>Copy Channel ID</strong>. Right-click each coworker → <strong>Copy User ID</strong>.</li></ol>
        <div className="form-grid"><label>Discord bot token<input type="password" {...field('discordToken')} placeholder={i.discord.configured ? 'Saved — leave blank to keep it' : 'Bot token from the Developer Portal'} autoComplete="new-password" /></label><label>Discord channel ID<input {...field('discordChannelId')} placeholder="Copy ID of a regular text channel" /></label></div>
        <button className="button secondary" disabled={!!busy} onClick={() => void run('discord', async () => { await save({ discordToken: form.discordToken, discordChannelId: form.discordChannelId }); await request('/api/discord/connect', {}); setMessage('Discord connected. Add coworkers below using their Discord user IDs.'); })}>{busy === 'discord' ? <LoaderCircle size={16} className="spin" /> : <Plug size={16} />}Save & connect Discord</button>
        {i.discord.error && <p className="inline-error">{i.discord.error}</p>}
        <p className="setup-note">All channel members can see proposals. Coworkers reply directly to their message or include its #DF reference. Dayflow checks the channel about every 6 seconds. No public URL is needed.</p>
      </section>}
      {tab === 'zoom' && <section className="setup-section" role="tabpanel" id="setup-zoom" aria-labelledby="tab-zoom">
        <div className="setup-heading"><span className="integration-icon zoom-icon"><Video size={23} /></span><div><h3>Zoom Team Chat</h3><p>Send to existing contacts from your authorized Zoom account.</p></div><span className={`pill ${i.zoom.connected ? 'green' : 'neutral'}`}>{i.zoom.connected ? 'Authorized' : 'Not authorized'}</span></div>
        <p className="setup-note">Use a user-managed General App with OAuth in <a href="https://marketplace.zoom.us/develop/create" target="_blank" rel="noreferrer">Zoom App Marketplace</a>. This connects persistent Team Chat, not the chat inside a video meeting. Your organization may require approval to install the app.</p>
        <div className="setup-step"><h4>1. Configure your Zoom app</h4><p>Add these user-level scopes:</p><div className="command-block scope-block"><code>user:read:user</code><code>team_chat:write:user_message</code><code>team_chat:read:list_user_messages</code></div><div className="form-grid"><label>Zoom client ID<input {...field('zoomClientId')} placeholder="Development client ID" /></label><label>Zoom client secret<input type="password" {...field('zoomClientSecret')} placeholder={i.zoom.configured ? 'Saved — leave blank to keep it' : 'Development client secret'} autoComplete="new-password" /></label></div><button className="button secondary" disabled={!!busy} onClick={() => void run('zoom-save', async () => { await save({ zoomClientId: form.zoomClientId, zoomClientSecret: form.zoomClientSecret, zoomRedirectBaseUrl: form.zoomRedirectBaseUrl }); setZoomUrl(''); setMessage('Zoom app settings saved. Set up its redirect URL next.'); })}>Save Zoom settings</button></div>
        <div className="setup-step"><h4>2. Set the authorization return address</h4><p>Start a temporary connection, then copy the exact URL below into your Zoom app’s <strong>OAuth Redirect URL</strong> and its OAuth allow list.</p><button className="button secondary" disabled={!!busy || i.zoom.tunnel.running} onClick={() => void run('zoom-tunnel', async () => { await request('/api/zoom/tunnel/start', {}); setZoomUrl(''); })}>{i.zoom.tunnel.running && !i.zoom.tunnel.url ? <LoaderCircle className="spin" size={16} /> : <Plug size={16} />}{i.zoom.tunnel.running ? 'Authorization connection running' : 'Start Zoom authorization connection'}</button>
          {i.zoom.redirectUrl && <div className="webhook-url"><label>Zoom OAuth Redirect URL<input readOnly value={i.zoom.redirectUrl} /></label><button className="icon-button" aria-label="Copy Zoom redirect URL" onClick={() => void copy(i.zoom.redirectUrl)}><Copy size={17} /></button></div>}
          {i.zoom.tunnel.error && <p className="inline-error">{i.zoom.tunnel.error}</p>}
          <details className="setup-instructions"><summary>Use an existing HTTPS connection</summary><label>Zoom public base URL<input {...field('zoomRedirectBaseUrl')} placeholder="https://your-host.example" /></label><p>Forward it to port 4319 and save Zoom settings. Only the authorization callback is public.</p></details>
        </div>
        <div className="setup-step"><h4>3. Authorize and verify</h4><p>Save the matching URL in Zoom first. Then create the authorization link here and open it with the Zoom account that will send meeting proposals.</p><div className="setup-buttons"><button className="button secondary" disabled={!!busy || !i.zoom.configured || !i.zoom.redirectUrl} onClick={() => void run('zoom-auth', async () => { const result = await request<{ url: string }>('/api/zoom/authorize', {}); setZoomUrl(result.url); })}>Create Zoom authorization link</button>{zoomUrl && <a className="button primary" href={zoomUrl} target="_blank" rel="noreferrer">Authorize on Zoom<ArrowUpRight size={15} /></a>}<button className="button secondary" disabled={!!busy} onClick={() => void run('zoom-check', async () => { await request('/api/zoom/connect', {}); setMessage('Zoom account and selected contact conversations checked.'); })}>Check Zoom connection</button></div>{i.zoom.account && <p className="connected-note"><CheckCheck size={15} /> Sending as {i.zoom.account}</p>}{i.zoom.error && <p className="inline-error">{i.zoom.error}</p>}</div>
        <p className="setup-note">Add each coworker’s existing Team Chat contact email below. Replies are checked about every 6 seconds. The temporary URL is only needed for authorization; if it changes before reconnecting, update it in Zoom.</p>
      </section>}
      {tab === 'model' && <section className="setup-section" role="tabpanel" id="setup-model" aria-labelledby="tab-model"><div className="setup-heading"><span className="integration-icon model-icon"><Sparkles size={22} /></span><div><h3>Open model · Ollama</h3><p>Drafts and reply interpretation stay on this computer.</p></div><span className={`pill ${i.llm.available ? 'green' : 'neutral'}`}>{i.llm.available ? 'Ready' : 'Not running'}</span></div><div className="form-grid"><label>Local Ollama URL<input {...field('ollamaUrl')} /></label><label>Model name<input {...field('ollamaModel')} /></label></div><div className="command-block"><code>ollama serve</code><code>ollama pull {form.ollamaModel}</code></div><button className="button secondary" disabled={!!busy} onClick={() => void run('model', async () => { await save({ ollamaUrl: form.ollamaUrl, ollamaModel: form.ollamaModel }); await request('/api/llm/check', {}); })}><Sparkles size={16} />Save & check model</button>{i.llm.error && <p className="inline-error">{i.llm.error}</p>}</section>}
      <section className="setup-section people-setup"><div className="setup-heading"><span className="integration-icon model-icon"><Users size={23} /></span><div><h3>Your meeting participants</h3><p>Choose Discord or Zoom per person. Telegram is reserved for you and Dayflow.</p></div><span className="pill neutral">{selected} selected</span></div>
        {!people.length && <div className="people-empty"><Users size={28} /><p>Add a coworker on Discord or Zoom Team Chat.<br />Their replies come back to you through Dayflow on Telegram.</p></div>}
        {people.map((person, index) => {
          const status = i.coworkers.find(p => p.id === person.id && p.platform === person.platform);
          return <div className={`person-editor ${person.platform}`} key={person.id}>
            <div className="person-editor-heading"><label className="check-label"><input type="checkbox" checked={person.enabled} onChange={e => updatePerson(person.id, { enabled: e.target.checked })} aria-label={`Include coworker ${index + 1}`} />Include in meeting</label><button className="icon-button" aria-label={`Remove coworker ${index + 1}`} onClick={() => setPeople(people.filter(p => p.id !== person.id))}><X size={16} /></button></div>
            <div className="form-grid"><label>Name<input aria-label={`Coworker ${index + 1} name`} value={person.name} onChange={e => updatePerson(person.id, { name: e.target.value })} placeholder="Alex" maxLength={60} /></label><label>Platform<select aria-label={`Coworker ${index + 1} platform`} value={person.platform} onChange={e => updatePerson(person.id, { platform: e.target.value as CoworkerPlatform, address: '' })}>{(['discord', 'zoom'] as CoworkerPlatform[]).map(platform => <option value={platform} key={platform}>{platformNames[platform]}</option>)}</select></label></div>
            <label>{person.platform === 'discord' ? 'Discord user ID' : 'Zoom contact email'}<input aria-label={`Coworker ${index + 1} destination`} value={person.address} onChange={e => updatePerson(person.id, { address: e.target.value.trim() })} placeholder={person.platform === 'discord' ? 'Right-click coworker → Copy User ID' : 'coworker@example.com'} /></label>
            {status && <div className="person-readiness"><span className={`pill ${status.ready ? 'green' : 'neutral'}`}>{!person.enabled ? 'Excluded' : status.ready ? 'Ready' : 'Needs setup'}</span>{person.enabled && !status.ready && <span>{status.reason}</span>}</div>}
          </div>;
        })}
        <div className="setup-buttons"><button className="text-button" disabled={people.length >= 8 || !!busy} onClick={() => setPeople([...people, { id: crypto.randomUUID(), name: '', platform: tab === 'zoom' ? 'zoom' : 'discord', address: '', enabled: true }])}>+ Add coworker</button><button className="button secondary" disabled={!!busy} onClick={() => void run('people', savePeople)}>{busy === 'people' ? <LoaderCircle size={16} className="spin" /> : <CheckCheck size={16} />}Save coworkers</button></div>
        <p className="setup-note">Up to 8 participants. Use one entry per person so they receive one request. Changing the recipient list requires a fresh approval. A failed or uncertain send stops the batch; Dayflow never retries it automatically.</p>
      </section>
      <section className="demo-guide"><span className="eyebrow">YOUR DEMO FLOW</span><h3>One approval. A coordinated conversation.</h3><ol><li>Pair your owner Telegram account and connect the platforms you need.</li><li>Add coworkers, finish their setup and click <strong>Save coworkers</strong>.</li><li>Select <strong>Live messages</strong> on the dashboard and advance the lunch scenario.</li><li>Review the recipients and approve on Telegram or the dashboard.</li><li>Coworkers reply on Discord or Zoom to their proposal or include its current <code>#DF-…</code> reference.</li><li>Watch the shared response list and receive the result privately on Telegram.</li></ol><p>Calendar, location, and travel estimates are replayed inputs in both modes. Real message delivery requires your platform accounts. Calendar invitations are not updated automatically.</p></section>
    </div><div className="dialog-footer"><span><ShieldCheck size={14} /> Credentials stay on this computer.</span><button className="button primary" onClick={close}>Back to my day<ArrowRight size={16} /></button></div>
  </dialog>;
}
